title: ML book
author: KBTU
logo: logo.png
execute:
  execute_notebooks: cache

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist

exclude_patterns: ["*/tasks.ipynb", "plotly_html.ipynb", "ISLP_datasets/*.ipynb",
                   "ensembling/bias_variance_handbook.ipynb", "notMNIST_small/*",
                   "mlp/MLP_notebook.ipynb", "mlp/keras.ipynb", "cnn/fashion-mnist-kaggle.ipynb"]

execute:
  timeout: 100
  allow_errors: true
  exclude_patterns:
    - 'python/basics/*'
    - 'linear_classificaton/multi_log_reg.ipynb'

sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinx_jupyterbook_latex
  config:
    bibtex_reference_style: author_year
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
